name: "Build"

on: [push]

env:
  IMAGE_NAME: ghcr.io/liatrio/envelope-game

jobs:
  get-tag:
    name: Get Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

  build-scan-push:
    name: Build, Scan, and Push
    needs: get-tag
    uses: blairdrummond/github-workflows/build/build-scan-push/build-scan-push.yaml@main
    with:
      push: false
      image_name: ${{ env.IMAGE_NAME }}
      image_tag: ${{ needs.get-tag.outputs.tag }}